name: Upload Python Package (Manual Trigger)

on:
  workflow_dispatch:
    inputs:
      # You can define input parameters that will be available when
      # manually triggering the workflow. These are optional.
      release_version:
        description: 'Release Version (e.g., 1.0.0)'
        required: false
        type: string
      run_tests:
        description: 'Run tests before building?'
        type: boolean
        default: true
      build_package:
        description: 'Build the distribution?'
        type: boolean
        default: true

  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && inputs.build_package == true)

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13.2"
          version: "0.6.11"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && inputs.run_tests == true)
        run: uv run pytest tests

      - name: Build release distribution
        if: success()
        run: uv build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/our-planner

    if: github.event_name == 'release' # Only publish on actual GitHub release

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/